### PR TITLE
update the version to 2018.10.0 in master

### PR DESCRIPTION
**Pull request by adnxn**
### Summary
Merging dev into master 

### Testing

New tests cover the changes: N/A

### Licensing

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yunhee-l** [comment]
this is just merging dev into master, correct? can you add some details in summary at least?

**Comment by adnxn** [comment]
> this is just merging dev into master, correct? can you add some details in summary at least?

will do.

**Comment by sharanyad** [comment]
not sure if this is the right place, but adding a note here. we should update [this](https://github.com/aws/amazon-ecs-agent/pull/1592/) test when we update cni-plugins in agent.

**Comment by adnxn** [comment]
> not sure if this is the right place, but adding a note here. we should update this test when we update cni-plugins in agent.

thanks for calling it out. i think moving forward we should be updating that test when we pull a new version of the plugin into the agent repo.

**Pull request merged**
